export const FETCH_PORTS = '[SERIAL] FETCH_PORTS'
export const LOADED_PORTS = '[SERIAL] LOADED_PORTS'

export const CONNECT_PORT = '[SERIAL] CONNECT_PORT'
export const CONNECTED_PORT = '[SERIAL] CONNECTED_PORT'
export const CONNECTION_ERROR = '[SERIAL] CONNECTION_ERROR'

export const DISCONNECT_PORT = '[SERIAL] DISCONNECT_PORT'
export const DISCONNECTED_PORT = '[SERIAL] DISCONNECTED_PORT'

export const PORT_MESSAGE = '[SERIAL] PORT_MESSAGE'
